import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Title from "../components/title";
import Weather from "../components/weatherPlaces";
import Footer from "../components/footer";
import SearchWeather from "../components/searchWeather";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Max's weather</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/sunicon.ico" />
      </Head>
      <Title />
      <Weather />
      <SearchWeather />
      <Footer />
    </>
  );
}
